fix build with MonadFailDesugaring
GHCs >= 8.6.1 give:

[4 of 5] Compiling Data.XCB.FromXML ( Data/XCB/FromXML.hs, /home/tycho/packages/xcb-types/dist-newstyle/build/x86_64-linux/ghc-8.6.3/xcb-types-0.9.0/build/Data/XCB/FromXML.o )

Data/XCB/FromXML.hs:373:17: error:
    • Could not deduce (MonadFail m) arising from a use of ‘expression’
      from the context: MonadPlus m
        bound by the type signature for:
                   structField :: forall (m :: * -> *).
                                  (MonadPlus m, Functor m) =>
                                  Element -> m StructElem
        at Data/XCB/FromXML.hs:343:1-66
      Possible fix:
        add (MonadFail m) to the context of
          the type signature for:
            structField :: forall (m :: * -> *).
                           (MonadPlus m, Functor m) =>
                           Element -> m StructElem
    • In a stmt of a 'do' block: expr <- expression exprEl
      In the expression:
        do nm <- el `attr` "name"
           (exprEl, caseEls) <- unconsChildren el
           expr <- expression exprEl
           (alignment, xs) <- extractAlignment $ caseEls
           ....

So we need some explicit MonadFails in various places.

Signed-off-by: Tycho Andersen <tycho@tycho.ws>