Hide <> from Prelude
recent GHCs give errors like:

/home/tycho/packages/xcb-types/Data/XCB/Pretty.hs:199:50: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Data/XCB/Pretty.hs:15:8-22
                             (and originally defined in ‘GHC.Base’)
                          or ‘Text.PrettyPrint.HughesPJ.<>’,
                             imported from ‘Text.PrettyPrint.HughesPJ’ at Data/XCB/Pretty.hs:19:1-32
    |
199 |                  hang (text "Reply:" <+> text nm <> char ',' <> toDoc n <+> toDoc repAlignment) 2 $
    |                                                  ^^

We need to hide <> from prelude in order to get this to compile correctly.

Signed-off-by: Tycho Andersen <tycho@tycho.ws>