mtl: relax version constraints
newer versions of ghc prefer newer versions of mtl, e.g. when building
xcffib I get:

Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: xcb-types-0.13.0 (user goal)
[__1] trying: mtl-2.3.1/installed-2.3.1 (dependency of xcb-types)
[__2] trying: transformers-0.6.1.0/installed-0.6.1.0 (dependency of mtl)
[__3] trying: base-4.18.2.0/installed-4.18.2.0 (dependency of xcb-types)
[__4] next goal: xcffib (user goal)
[__4] rejecting: xcffib-1.5.0 (conflict: mtl==2.3.1/installed-2.3.1, xcffib =>
mtl>=2.2.2 && <2.3)
[__4] rejecting: xcffib-1.4.0, xcffib-1.3.0, xcffib-1.2.0, xcffib-1.1.2,
xcffib-1.1.1, xcffib-1.1.0, xcffib-1.0.0, xcffib-0.12.1, xcffib-0.12.0,
xcffib-0.11.1, xcffib-0.11.0, xcffib-0.10.0, xcffib-0.9.0, xcffib-0.8.1,
xcffib-0.8.0, xcffib-0.7.0, xcffib-0.6.0, xcffib-0.5.1, xcffib-0.5.0,
xcffib-0.4.2, xcffib-0.4.1, xcffib-0.4.0, xcffib-0.3.6, xcffib-0.3.5,
xcffib-0.3.4, xcffib-0.3.3, xcffib-0.3.2, xcffib-0.3.1, xcffib-0.3.0,
xcffib-0.2.5, xcffib-0.2.4, xcffib-0.2.2, xcffib-0.2.1, xcffib-0.2.0,
xcffib-0.1.5 (constraint from user target requires ==1.5.0)
[__4] fail (backjumping, conflict set: mtl, xcffib)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, semigroupoids, transformers,
comonad, xcffib, either, transformers-compat, mtl, semigroupoids:comonad,
distributive, semigroupoids:distributive, xcb-types
Try running with --minimize-conflict-set to improve the error message.

Let's relax these constraints so we can use mtl 2.3.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>